name: CI
on:
  pull_request:
  push:
    branches:
      - staging
      - 'v*'
env:
  node_version: "12.x"

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci --prefer-offline
      - run: npm run package

  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - run: npm audit --audit-level=critical

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci --prefer-offline
      - run: npm run lint

# When tests are added to the code uncomment
#  test:
#    name: Test
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Set up Node.js
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ env.node_version }}
#          cache: npm
#          cache-dependency-path: '**/package-lock.json'
#      - run: npm ci --prefer-offline
#      - run: npm test
