name: Test
on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Slack
        uses: ./
        with:
          status: ${{ job.status }}
          channel: '#slack-bot-testing'
          webhook-url: ${{ secrets.slack_webhook_url }}
